### ISSUE TITLE
Unexpected error message in mobile app after verifying

### ISSUE THREAD

**Issue by whatSocks** [resonatecoop/verifiable-credentials#1]
![IMG_9219BF583423-1](https://user-images.githubusercontent.com/2731744/125226777-b4725000-e29f-11eb-8eff-52258b1f2c62.jpeg)

error message after verifying, but everything seemed to work as expected

**Comment by angusmcleod** [comment]
@whatSocks Indeed! Thanks for the report. It's an issue with mutual authentication which I'm working on resolving. Hope to have a fix for this in a few weeks. While this is a real issue I'm going to close this "issue", as it's not quite reflective of the er "issue" at hand here. But thanks :)
